  bugfix/fix-category-click[m
  bugfix/fix-redirect-reg-main[m
  bugfix/fix-redirects[m
  bugfix/fix-set-addresses[m
  bugfix/registration-error404[m
  develop[m
  feature/add-pagination-catalog[m
  feature/add-reset-btn-filter[m
  feature/catalog-configure[m
  feature/catalog-view[m
  feature/fetch-render-categories[m
  feature/fetch-render-products[m
  feature/intagrate-cart-with-catalog[m
  feature/logout-and-login-errors[m
  feature/product-client[m
  feature/render-breadcrumb[m
  feature/render-filter-color[m
  feature/render-filters[m
  feature/router-categories[m
  feature/user-auth-api[m
  main[m
  sprint_1[m
  sprint_2[m
  sprint_3[m
* [32msprint_4[m
